//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseBall_Stats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hitting_Stats
    {
        public int HittingStatId { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<int> PA { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> DB { get; set; }
        public Nullable<int> TRP { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<int> CS { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<decimal> BA { get; set; }
        public Nullable<decimal> OPB { get; set; }
        public Nullable<decimal> SLG { get; set; }
        public Nullable<decimal> OPS { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> StatYear { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> RBI { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
